-- Baseline schema as of the pre-teacher-signup release.
--
-- This captures everything Hibernate's `ddl-auto=update` had been generating up to this
-- point. Existing production databases should baseline against this version (Flyway's
-- `flyway.baseline-on-migrate=true`) so V2 and beyond apply cleanly without recreating
-- already-existing tables.
--
-- Targets PostgreSQL 14+. Uses SQL-standard identity columns so the same DDL is also
-- accepted by H2 2.x (used in dev when DB_DRIVER is not overridden).

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(32)  NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP
);

CREATE TABLE IF NOT EXISTS courses (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    term       VARCHAR(255),
    teacher_id BIGINT       NOT NULL REFERENCES users(id),
    archived   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_courses_teacher_id ON courses(teacher_id);

CREATE TABLE IF NOT EXISTS sessions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id     BIGINT       NOT NULL REFERENCES courses(id),
    join_code     VARCHAR(255) NOT NULL UNIQUE,
    activity_mode VARCHAR(32)  NOT NULL,
    status        VARCHAR(32)  NOT NULL,
    started_at    TIMESTAMP    NOT NULL,
    ended_at      TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_sessions_course_id ON sessions(course_id);
CREATE INDEX IF NOT EXISTS idx_sessions_status ON sessions(status);

CREATE TABLE IF NOT EXISTS session_snapshots (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    BIGINT    NOT NULL REFERENCES sessions(id),
    green_count   BIGINT    NOT NULL,
    yellow_count  BIGINT    NOT NULL,
    red_count     BIGINT    NOT NULL,
    student_count BIGINT    NOT NULL,
    captured_at   TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_session_snapshots_session_id ON session_snapshots(session_id);

CREATE TABLE IF NOT EXISTS student_accounts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    display_name  VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS student_participants (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id         BIGINT       NOT NULL REFERENCES sessions(id),
    display_name       VARCHAR(255) NOT NULL,
    student_account_id BIGINT       REFERENCES student_accounts(id),
    joined_at          TIMESTAMP    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_student_participants_session_id ON student_participants(session_id);

CREATE TABLE IF NOT EXISTS stoplight_responses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id  BIGINT      NOT NULL REFERENCES student_participants(id),
    session_id      BIGINT      NOT NULL REFERENCES sessions(id),
    stoplight_value VARCHAR(32) NOT NULL,
    submitted_at    TIMESTAMP   NOT NULL,
    CONSTRAINT uq_stoplight_responses_participant_session UNIQUE (participant_id, session_id)
);
CREATE INDEX IF NOT EXISTS idx_stoplight_responses_session_id ON stoplight_responses(session_id);
